#### NumPy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays  and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np # Alias

## create array using numpy
## create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
print(arr2.shape)

(5,)


In [9]:
# 2D Array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
