#### NumPy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays  and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [11]:
import numpy as np # Alias

## create array using numpy
## create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
print(arr2.shape)

(5,)


In [9]:
# 2D Array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [3]:
arr3 = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
                 [[4, 5, 6], [5, 6, 7], [6, 7, 8]],
                 [[7, 8, 9], [8, 9, 10], [9, 10, 11]]])


In [4]:
print(arr3)

[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [5]:
print(arr3.shape)

(3, 3, 3)


In [13]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [14]:
np.arange(0, 10, 2).reshape(5, 1) # 5 rows, 1 column - 2D array


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3, 4)) # 3 rows, 4 columns - 2D array with 1s

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## identity matrix 
np.eye(3) #diagonal elements are 1s, remaining are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)
print("Shape:", arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size (in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions:  2
Size (number of elements):  6
Data Type:  int64
Item Size (in bytes):  8


In [19]:
## Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

## Element wise Addition
print("Addition:", arr1 + arr2)


## Element wise Subtraction
print("Subtraction:", arr1 - arr2)

## Element wise Addition
print("Multiplication:", arr1 * arr2)

## Element wise Addition
print("Division:", arr1 / arr2)


Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Functions